name: AI Code Review
on:
 pull_request:
   types: [opened, edited, reopened]
jobs:
 ai-code-review:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Run AI Code Review
       uses: actions/github-script@v5
       with:
         script: |
           const { Octokit } = require("@octokit/rest");
           const axios = require("axios");
           const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
           const { data: pullRequest } = await octokit.pulls.get({
             owner: context.repo.owner,
             repo: context.repo.repo,
             pull_number: context.payload.pull_request.number,
           });
           const code = pullRequest.body; // You can modify this to get the code you want to review
           const response = await axios.post('https://api.openai.com/v1/chat/completions', {
             model: "gpt-3.5-turbo",
             messages: [
               { role: "user", content: `Please review the following code and provide feedback:\n\n${code}` }
             ],
             max_tokens: 150
           }, {
             headers: {
               'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
               'Content-Type': 'application/json'
             }
           });
           const reviewFeedback = response.data.choices[0].message.content;
           await octokit.issues.createComment({
             owner: context.repo.owner,
             repo: context.repo.repo,
             issue_number: context.payload.pull_request.number,
             body: `### AI Code Review Feedback\n\n${reviewFeedback}`
           });
       env:
         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
